title: Ali KarÄiÄ‡
theme: jekyll-theme-minimal
description: Political Science PhD Candidate
ğŸ“§ [alikarcic@uni.au.dk](mailto:au567641@ps.au.dk)  
ğŸ”— [ORCID: 0000-0002-XXXX-XXXX](https://orcid.org/0000-0002-XXXX-XXXX)
logo: /files/photo_new-modified.png
